[package]

name = "gestalt"
version = "0.0.1"
authors = [ "Samuel Cutlip <gyro@zettabyte.ws>" ]

[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-g`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false        # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled
codegen-units = 1  # controls whether the compiler passes `-C codegen-units`
                   # `codegen-units` is ignored when `lto = true`
panic = 'unwind'   # panic strategy (`-C panic=...`), can also be 'abort'

[dependencies]
num = "0.1.37"
time = "*"
cgmath = { git = "https://github.com/brendanzab/cgmath.git", rev = "3e6974b" }

serde = { version = "1.0.2", features = ["std"] }
serde_yaml = "0.7.0"
serde_derive = "1.0.2"

lazy_static = "0.2.8"
specs = "0.8.1"
string_cache = "0.5.0"
linear-map = { git = "https://github.com/contain-rs/linear-map" }

glium = "*"
image = "0.10.0"
shader_version = "0.2.1"

hlua = "0.4.0" # This is our Lua until I can be bothered to wrap LuaJIT. It's Lua 5.2, so LuaJIT may just be a drop-in replacement. 
# hlua =  { git = "https://github.com/tomaka/hlua.git", rev = "a6b3bc8" } # Git repo version is necessary for fine-grained library open methods, such as "open_string()"

# piston = "0.32.0"
# pistoncore-glutin_window = "0.37.0"
# gfx = "0.16.0"
# gfx_core = "0.7.0"
# gfx_device_gl = "0.14.0"
# camera_controllers = "0.21.0"
# fps_counter = "0.2.0"

# conrod = "0.38.2"
