sudo: false
dist: bionic
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.36.0
os:
  - linux
  - osx
  - windows
addons:
  apt:
    packages:
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - git submodule update --init --recursive

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - cargo build --manifest-path imgui-winit-support/Cargo.toml --no-default-features --features winit-19
  - cargo test --manifest-path imgui-winit-support/Cargo.toml --no-default-features --features winit-19
  - cargo build --manifest-path imgui-winit-support/Cargo.toml --no-default-features --features winit-20
  - cargo test --manifest-path imgui-winit-support/Cargo.toml --no-default-features --features winit-20
  - cargo build --all --verbose --manifest-path imgui-examples/Cargo.toml
  - cargo test --all --verbose --manifest-path imgui-examples/Cargo.toml
  - cargo build --all --verbose --manifest-path imgui-gfx-examples/Cargo.toml
  - cargo test --all --verbose --manifest-path imgui-gfx-examples/Cargo.toml
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then cargo build --all --verbose --no-default-features --features directx --manifest-path imgui-gfx-examples/Cargo.toml; fi
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then cargo test --all --verbose --no-default-features --features directx --manifest-path imgui-gfx-examples/Cargo.toml; fi
