[package]
name = "gestalt"
version = "0.0.1"
authors = ["gyro", "trashbyte"]
edition = "2018"

[dependencies]
cgmath = { version = "0.17.0", features = [ "swizzle" ] }

time = "0.1.42"
rand = "0.7.2"
noise = "0.6.0"
fine_grained = "0.1.2"
smallvec = "0.6.12"
fnv = "1.0.6"

parking_lot = "0.9.0"
crossbeam = "0.7.2"
log = "0.4.8"
chrono = "0.4.9"
lazy_static = "1.4.0"
num = "0.2.0"
string_cache = "0.8.0"
clap = "2.33.0"
linear-map = "1.2.0"

serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
toml = "0.5.5"

rgb = "0.8.14"
hashbrown = "0.6.3"

image = "0.22.3"
vek = "0.9.10"
winit = "0.19.4"

vulkano = "0.16.0"
vulkano-shaders = "0.16.0"
rusttype = { version = "0.8.1", features = ["gpu_cache"] }

generational-arena = { version = "0.2.6", features = ["serde"] }

#TODO: Rewrite VoxelArray to use compile-time size.
#typenum = "1.10.0"
#generic-array = "0.13.2"

[build-dependencies]
rerun_except = "0.1.0"
