[package]
name = "gestalt"
version = "0.0.1"
authors = ["gyro", "trashbyte"]
edition = "2018"

[dependencies]
cgmath = { version = "0.17.0", features = [ "swizzle" ] }

time = "0.1.42"
rand = "0.7.2"
noise = "0.6.0"
fine_grained = "0.1.2"
smallvec = "0.6.12"

parking_lot = "0.9.0"
crossbeam = "0.7.2"
chrono = "0.4.9"
lazy_static = "1.4.0"
num = "0.2.0"
string_cache = "0.8.0"
clap = "2.33.0"
linear-map = "1.2.0"

serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
toml = "0.5.4"

rgb = "0.8.14"
hashbrown = "0.6.2"

image = "0.22.3"
winit = "0.19.4"
vek = "0.9.9"
swsurface = "0.1.2"
euc = "0.4.2"

flame = "0.2.2"

imgui = "0.2.1"
clipboard = "0.5"

lumberjack = { path = "../lumberjack" }
phosphor = { path = "../phosphor" }
toolbox = { path = "../toolbox" }
make_names = { path = "../make_names" }

#tramp = "*"

#TODO: Rewrite VoxelArray to use compile-time size.
#typenum = "1.10.0"
#generic-array = "0.13.2"

[build-dependencies]
walkdir = "2.2.9"
regex = "1.3.1"
