[package]
name = "gestalt_proc_macros"
version = "0.0.1"
authors = ["Emily 'Gyro' C. <gyrocoder@gmail.com>", "trashbyte"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "~1.0.40"
syn = { version = "~1.0.98", features = ["parsing", "proc-macro"] }
quote = "~1.0.20"
